# services:
#   server:
#     container_name: collabo-server
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#       target: runner
#     volumes:
#       - ./server:/app
#       - /build/node_modules
#     networks:
#       - Collobo
#     ports:
#       - "3000:3000"

#   client:
#     container_name: collabo-client
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#       target: runner
#     volumes:
#       - ./client:/app
#       - /build/node_modules
#     networks:
#       - Collabo
#     ports:
#       - "5173:5173"
#     depends_on:
#       - server

# networks:
#   Collabo:
#     driver: bridge
